# service-accounts.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-gateway-sa # ID Badge for api-gateway
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: phi-service-sa   # ID Badge for phi-service
  namespace: default
# Note: We don't need one for audit-service as it only receives traffic in this policy
# Note: We don't strictly need one for frontend for this policy