# === 1. Service Account for Audit Service ===
apiVersion: v1
kind: ServiceAccount
metadata:
  name: audit-service-sa
  namespace: default
  annotations:
    # This links this KSA to its Google Service Account (GSA)
    iam.gke.io/gcp-service-account: audit-gsa@elevance-demo-project.iam.gserviceaccount.com

---
# === 2. Service Account for PHI Service ===
apiVersion: v1
kind: ServiceAccount
metadata:
  name: phi-service-sa
  namespace: default
  annotations:
    iam.gke.io/gcp-service-account: phi-gsa@elevance-demo-project.iam.gserviceaccount.com

---
# === 3. Service Account for API Gateway ===
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-gateway-sa
  namespace: default
  annotations:
    iam.gke.io/gcp-service-account: api-gateway-gsa@elevance-demo-project.iam.gserviceaccount.com

---
# === 4. Service Account for Frontend ===
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: default
  annotations:
    iam.gke.io/gcp-service-account: frontend-gsa@elevance-demo-project.iam.gserviceaccount.com